spring.application.name=ticket_analyser


server.port= 8083
spring.ai.openai.api-key=${GROQ_API_KEY:mock-groq-key}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
spring.ai.openai.chat.options.temperature=0.5

gemini.api.key=${GEMINI_API_KEY:mock-gemini-key}
gemini.api.completions.path=/chat/completions
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/openai
gemini.api.model.name= gemini-2.5-flash